### PR TITLE
[IMP] account_cutoff_prepaid: Add fields explicitely on move line form+tree view inside account.move

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @antespi @janetrp

**Comment by rafaelbn** [comment]
Functional review , it looks good but runbot fails

**Comment by pedrobaeza** [comment]
@sbidoul, @adrienpeiffer, can you review?

**Comment by sbidoul** [comment]
Code looks good. I'm a bit afraid this tree view will become too crowded. I'll test on runbot when ready.

**Comment by pedrobaeza** [comment]
Yeah, I know, but it's a must because you can't access form view from the account.move view.

**Comment by rafaelbn** [comment]
Tested in runbot :+1:

**Comment by rafaelbn** [comment]
ping @antespi

**Comment by sbidoul** [comment]
@pedrobaeza @rafaelbn I'm curious, do you have users willing to enter start/end dates on miscellaneous operations? Ours are happy with having that on invoices only.

**Comment by pedrobaeza** [comment]
Yes, because there are some manual entries that they need to enter/modify.

**Comment by sbidoul** [comment]
@pedrobaeza Yeah but I mean which type of entries? I my experience all entries that are subject to cutoff are also invoices. So I'm curious.

**Comment by pedrobaeza** [comment]
I didn't remember well, but when seeing with the customer, we ended up with this need. @rafaelbn, do you remember?

**Comment by pedrobaeza** [comment]
@sbidoul, I have remembered the use case: some insurances payments are registered via bank statement, which generates an account entry. This doesn't have any invoices, but goes directly against an expense account. This expense has to be cutoff, and the only way to put the dates we have is through journal entry screen.

**Comment by sbidoul** [comment]
Ok, thanks a lot for the explanation. Let's see if user complain about the crowded screen or not.

**Pull request merged**
