### PR TITLE
[14.0][FIX] fiscal year multi company rule

### PR DESCRIPTION
**Pull request by GSLabIt**
Fix issue related to multi company permission

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Comment by francesco-ooops** [comment]
@tafaRU @sergiocorato can you take a look? thanks!

**Comment by odooNextev** [comment]
Functional ok

**Review by odooNextev — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/accounting-maintainers this is a fix to a blocking bug with some specific multi-company configurations. 

What do you think?

**Review by grindtildeath — APPROVED** [review]

**Pull request merged**
