### PR TITLE
[WIP][MIG][10.0] account_fiscal_year_closing

### PR DESCRIPTION
**Pull request by angelmoya**
- [ ] #50

@pedrobaeza I tried to do cherry-pick to maintain commits, but there are conflicts and finally I'm not sure if process was done right.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Indeed there's something strange, as the commits are reversed. Maybe that's the problem. Try again to use the commits, but taking care of keeping the order.

About the module itself in 10.0. I see that the onchange bug is still there, so we should find it and notify to Odoo.

**Comment by pedrobaeza** [comment]
Blocked due to odoo/odoo#20163

**Comment by JordiBForgeFlow** [comment]
This PR https://github.com/PESOL/account-closing/pull/1/files fixes the problem for v10. @angelmoya please review and merge in your branch.

**Comment by pedrobaeza** [comment]
That's not really a solution, but a workaround. I'm not taking that direction, but a button for bringing template. Please wait until I fix that and other changes that I'm making in v9, and we forward port all to v10.

**Comment by JordiBForgeFlow** [comment]
OK

**Comment by pedrobaeza** [comment]
@jbeficent 9.0 version is now finished with a better workaround for loading the template. Are you going to forward-port it soon? If not, please tell me as I need it also in v10.

**Comment by JordiBForgeFlow** [comment]
Yes, will do today

**Comment by pedrobaeza** [comment]
Closing in favor of #57

**Pull request closed without merging**
