### PR TITLE
[16.0][MIG] account_cutoff_picking (ex account-cutoff_accrual_picking)

### PR DESCRIPTION
**Pull request by alexis-via**
The migration has been made from this v14 PR that adds prepaid support https://github.com/OCA/account-closing/pull/225

### CODE REVIEW

**Comment by yankinmax** [comment]
@alexis-via can you pls rebase to fix the build and update README of `account_cutoff_base` to point to the new module name instead of `account_cutoff_accrual_picking`
Thanks

**Comment by alexis-via** [comment]
Here you go: https://github.com/OCA/account-closing/pull/232

**Review by yankinmax — APPROVED** [review]

**Comment by yankinmax** [comment]
ref: MNT-183

**Comment by simahawk** [comment]
@alexis-via LG. Can you please rewrite the last commit to remove "from v14 branch 14-cutoff_picking-add_pr".
I would link the PR https://github.com/OCA/account-closing/pull/225 in the commit description instead.

**Comment by dzungtran89** [comment]
lgtm, thank you

**Comment by yankinmax** [comment]
@alexis-via can you pls update with @simahawk suggestion?
https://github.com/OCA/account-closing/pull/230#issuecomment-1436687565

**Comment by simahawk** [comment]
Replaced by #235 to speed it up

**Pull request closed without merging**
