### PR TITLE
[MIG] account_cutoff_start_end_dates: Migration to 16.0

### PR DESCRIPTION
**Pull request by dzungtran89**
https://github.com/OCA/account-closing/issues/203

Needs
- https://github.com/OCA/account-closing/pull/213

### CODE REVIEW

**Comment by alexis-via** [comment]
I made a PR to improve this PR:
https://github.com/dzungtran89/account-closing/pull/2

**Comment by yankinmax** [comment]
@dzungtran89  can you pls rebase to fix the build?

**Comment by dzungtran89** [comment]
@yankinmax the PR has been updated, could you please check?

**Review by yankinmax — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
