### PR TITLE
[14.0][MIG] account_cutoff_base (now includes account_cutoff_accrual_base)

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by SimoneVagile — CHANGES_REQUESTED** [review]
Can you add any other tests?

I see you merged `account_cutoff_accrual_base` in this.
You may complete tests with [https://github.com/OCA/account-closing/blob/12.0/account_cutoff_accrual_base/tests/test_account_cutoff.py](https://github.com/OCA/account-closing/blob/12.0/account_cutoff_accrual_base/tests/test_account_cutoff.py) and others, FE state changing

**Comment by alexis-via** [comment]
@SimoneVagile I got back the tests from account_cutoff_accrual_base

**Comment by tarbib** [comment]
Approved

**Review by tarbib — APPROVED** [review]

**Review by fclementic2c — COMMENTED** [review]
Test 👌

**Pull request merged**
