### PR TITLE
[17.0][MIG] account_cutoff_start_end_dates: Migration to 17.0

### PR DESCRIPTION
**Pull request by lethuthao2403**
ref: [BSRD-700](https://jira.camptocamp.com/browse/BSRD-700)

### CODE REVIEW

**Comment by gurneyalex** [comment]
hello @lethuthao2403

I'm merging https://github.com/OCA/account-closing/pull/284 and https://github.com/OCA/account-closing/pull/286
Can you rebase and remove the unreleased dependencies?

**Comment by lethuthao2403** [comment]
> hello @lethuthao2403
> 
> I'm merging #284 and #286 Can you rebase and remove the unreleased dependencies?

@gurneyalex the PR has been updated! Thanks.

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
