### PR TITLE
[MIG][9.0] Migrate account_cutoff_accrual_base

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis status

**Comment by sylvainvh** [comment]
Hi,

I just created a new Pull Request on this branch with some test to improve the code coverage.

**Comment by grindtildeath** [comment]
@sylvainvh Thank you !

**Comment by sbidoul** [comment]
Note there is a migration in progress for 10.0 here https://github.com/OCA/account-closing/
The resulting should be almost identical fro 9.0 and 10.0.

cc/ @adrienpeiffer @cedric-pigeon

**Comment by yvaucher** [comment]
compared to https://github.com/OCA/account-closing/pull/43

here we need 
https://github.com/OCA/account-closing/pull/43/commits/28e56057ac13d4c8e34317d12c63d70755e8104b


@Cedric-Pigeon do we need this here ? not sure what this commit is about
https://github.com/OCA/account-closing/pull/43/commits/d1e1a89e1c3ff69f1d851c4d1f895076ba9d3eba

**Comment by sbidoul** [comment]
@yvaucher don't worry about the setup directory if you don't need it, it will be autogerated. Do NOT backport these commits as the structure is different in 8/9 and 10.

I'm porting the test to the 10.0 branch.

**Comment by sbidoul** [comment]
It looks like this PR is missing the default journals from [8.0](https://github.com/OCA/account-closing/commit/99c046f50d4c423d19189cb1c8895a2669c4ccf9) and #43.

**Pull request closed without merging**
