### PR TITLE
add oca_dependencies.txt

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please remove the travis lines: https://github.com/OCA/account-closing/blob/9.0/.travis.yml#L32

**Comment by sbidoul** [comment]
@pedrobaeza done

**Comment by pedrobaeza** [comment]
Why adding reporting-engine?

**Comment by sbidoul** [comment]
Because report_xls is a dependency of account_asset_management.

**Comment by pedrobaeza** [comment]
But account_asset_management is not installed...

**Comment by sbidoul** [comment]
But it is imported. I've seen an `import report_xls`  fail earlier today in this project.

**Comment by pedrobaeza** [comment]
Indeed the calls are not protected according current guidelines, but we can stay as is for now.

I fast-track it to get green branches.

**Pull request merged**
