### PR TITLE
[MIG] account_multicurrency_revaluation: Migration to 14.0

### PR DESCRIPTION
**Pull request by phuctranfxvn**

### CODE REVIEW

**Comment by hugho-ad** [comment]
@hbto 
could you review this please?

**Comment by hbto** [comment]
Currently there is a PR https://github.com/OCA/account-closing/pull/149

Where some fixes has been made I would like if those Changes are approved that they are integrated.

Regards.

**Comment by simahawk** [comment]
> Currently there is a PR #149
> 
> Where some fixes has been made I would like if those Changes are approved that they are integrated.
> 
> Regards.

@phuctranerp have you seen this?

**Comment by simahawk** [comment]
> @hbto
> could you review this please?

you could drop a review as well. If you don't have tech skills you could review its functional behavior :wink:

**Comment by mmequignon** [comment]
migration looks good, however I'm agree with @hbto , would be fine to include #149

**Comment by hailangvn** [comment]
Good day @hbto, @simahawk, @mmequignon, we will work on this one soon.

**Comment by simahawk** [comment]
@hailangvn @phuctranerp ping :)

**Comment by hailangvn** [comment]
Good day @simahawk, we are still working on this.

**Comment by hailangvn** [comment]
The forward port for 13.0 is https://github.com/OCA/account-closing/pull/183. I am still working on 14.0.

**Comment by hailangvn** [comment]
This is ready for reviewing. Thanks.

**Review by grindtildeath — APPROVED** [review]
Looks good from what I tested :+1:

**Review by simahawk — APPROVED** [review]

**Pull request merged**
