### PR TITLE
[WIP][11.0][FIX] fix account_multicurrency_revaluation test

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by fclementic2c** [comment]
@sbidoul ping

**Comment by sbidoul** [comment]
Looks like it's still red.

**Comment by fclementic2c** [comment]
@grindtildeath  Can you help on this ?

**Comment by grindtildeath** [comment]
@oleksandrpaziuk Please check https://github.com/OCA/account-closing/pull/77

**Comment by grindtildeath** [comment]
Please close in favour of #79

**Pull request closed without merging**
