### PR TITLE
[FIX][16.0]account-closing bad display for field "must_have_date"

### PR DESCRIPTION
**Pull request by DorianMAG**
Add group for field must_have_date

### CODE REVIEW

**Comment by DorianMAG** [comment]
hi @alexis-via 
Little fix for bad display field
https://github.com/OCA/account-closing/issues/251
@flotho Can you make a re review plz ? :)

**Review by JulienMartinez — APPROVED** [review]
tested in local with other modules
LGTM

**Comment by DorianMAG** [comment]
@JulienMartinez 
Thx ! :)

**Review by flotho — APPROVED** [review]
easy code LGTM

**Comment by flotho** [comment]
Hi @alexis-via , here is an easy fix, any chance to have a review ?

**Pull request closed without merging**
