### PR TITLE
[10.0] account_multicurrency_revaluation - Fix css file path

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Review by grindtildeath — APPROVED** [review]
Please also bump version number as it wasn't done after merging the report part.

**Comment by yvaucher** [comment]
@grindtildeath just bumped version here:

https://github.com/OCA/account-closing/commit/c2741f246795392dec7e14e17dd592b77635a765

This one will probably be the 10.0.2.0.1 version

**Comment by yvaucher** [comment]
@grindtildeath added version change here, ready to be merged

**Comment by yvaucher** [comment]
ping @OCA/accounting-maintainers this one is a on line fix for the CSS file

During migration of the report a path wasn't set correcly. Can this be reviewed/merged?

Thanks

**Review by pedrobaeza — APPROVED** [review]
OK, we can fast-track this

**Comment by yvaucher** [comment]
@pedrobaeza thanks

**Pull request merged**
