### PR TITLE
[12.0][FIX] account_fiscal_year_closing: tests should not use fixed dates

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@hbto @pedrobaeza can we fast-track this so I can rebase #149 ?

**Review by sergiocorato — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
Why are you changing this? Tests must use fixed data, and not variable one. Any problem you think on it's not due to this.

**Comment by alexey-pelykh** [comment]
@pedrobaeza well, w/o this change tests just fail 🤷‍♂️ With change for dates to be "this year", tests don't fail. I'm no expert in year closing, but that's as close as I could get, and last year (when fixed dates were "this year"), tests were not failing as well.

**Comment by sergiocorato** [comment]
If I had time when I ported it, I would have done it myself. BTW, if @alexey-pelykh resolved an issue in another module with this change, perhaps there is something wrong somewhere.

**Comment by alexey-pelykh** [comment]
@sergiocorato w/o this change, this specific module tests failed on original 12.0 branch, so nothing to do with other modules I guess

**Comment by pedrobaeza** [comment]
The usual problem with variable dates comes with leap years not returning the same expected results, but in general, is not good to not control input data for having always the same output.

On the other hand, fixing dates can make that methods that uses date references like `today`, `now` and so on to not be testable. Solution is to mock the function to return a fixed date, and in v14, you can use `freezegun` library, as included in Odoo core.

**Comment by sergiocorato** [comment]
@pedrobaeza Perhaps I understand your position, but as you see in the code, @alexey-pelykh is using fixed dates with `month` and `day`, not `today` as-is. Variability added is only regarding the year.

**Comment by pedrobaeza** [comment]
OK, it was just a suggestion for keeping things with good guidelines, but there are tests with relative dates all around OCA, and they occasionally blown away, but others not, so we will know if it happens with this one.

**Pull request merged**
