### PR TITLE
[10.0][mig][account_fiscal_year_closing]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Standard migration from 9.0

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @pedrobaeza I propose to add full tests in v11.

**Comment by pedrobaeza** [comment]
OK, good for me, but you're missing the 10.0 migration commit (changing at least version numbers).

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Yes, sorry. Forgot to commit the changes

**Review by pedrobaeza — APPROVED** [review]
As this is basically the same as v9, we can merge it right now.

**Pull request merged**
