### PR TITLE
[MIG][10.0]account_cutoff_accrual_base migration

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Comment by yvaucher** [comment]
Please add those tests here https://github.com/OCA/account-closing/pull/42/commits/c43402e9d6fa62ac31fa15f16a78b91e51cf6cdd

**Comment by sbidoul** [comment]
@yvaucher I included the test here.

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
@sbidoul would have been better to cherry-pick the commits to keep the historic but ok you have my approval. Thanks

**Comment by sbidoul** [comment]
@yvaucher I usually pay attention to this. I now preserved the author in d312c21 and rebased.

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
