### PR TITLE
[Fix] user company_id instead of journal company_id

### PR DESCRIPTION
**Pull request by kenvac**
Fix for issue #1

### CODE REVIEW

**Comment by bwrsandman** [comment]
Is this for the 8.0 branch?

**Comment by pedrobaeza** [comment]
:+1:

**Comment by kenvac** [comment]
Its version 7.0. But I'm sure the bug exist for version 8.0 as well.

**Comment by bwrsandman** [comment]
@kenvac just so you know this PR is proposed to the master branch which is not 7.0

I suggest you make another PR for 7.0.

You can do so with the same branch:  kenvac:master but select  OCA:7.0 as the base branch

**Comment by pedrobaeza** [comment]
@bwrsandman, you should consider both branches, not only 7.0, because bug will be also there.

**Comment by bwrsandman** [comment]
Porting process of 8.0 for these modules has not started: last commit on master is in January

If there is a merge here, it is likely that commit will be lost or squashed when that process happens.

**Comment by pedrobaeza** [comment]
Yeah, but if we don't include this patch, v8.0 will have a regression against the v7 branch. The other alternative is to rebase from 7.0 when integrated.

**Comment by bwrsandman** [comment]
Rebase, reset or merge, we could even create 8.0 from 7.0.
Since the nomenclature of version branches for 8.0 isn't clear, I wouldn't trust commiting here unless it's oviously the proper place, and in this case, it was a wrong base branch.

Note that if you checkout odoo master, it will identify as Odoo 9 Alpha 1.

**Comment by pedrobaeza** [comment]
OK, let's wait until we have it clear.

Regards.

**Comment by guewen** [comment]
The 8.0 branch is there so this PR should be submitted again against the 8.0 branch.

**Pull request closed without merging**
