### PR TITLE
14.0 mig account cutoff prepaid

### PR DESCRIPTION
**Pull request by iwkse**
Hi,
I've noticed this module adds functionalities that are also present in account_cutoff_base.
Should it be removed from base and leave it just in this module?

### CODE REVIEW

**Comment by iwkse** [comment]
@pedrobaeza any feedback about the duplicate functionalities?

**Comment by pedrobaeza** [comment]
I'm not using these modules, and no time to check, so I leave to others the discussion.

**Comment by iwkse** [comment]
> I'm not using these modules, and no time to check, so I leave to others the discussion.

@pasgou do you know about it or can you point out to whom I should ask?

thank you

**Comment by pasgou** [comment]
I use Odoo 12.0 and these module is useful to calculate the expenses and revenus that begin in a fiscal year and finish after the fiscal year.

I don't know about duplicate functionalities. Duplicate between what and what?

**Comment by iwkse** [comment]
> I use Odoo 12.0 and these module is useful to calculate the expenses and revenues that begin in a fiscal year and finish after the fiscal year.
> 
> I don't know about duplicate functionalities. Duplicate between what and what?

That's in the account_cutoff_base, v14.0
https://github.com/OCA/account-closing/blob/5e036880d06975e2719247153b485225bbd49f9a/account_cutoff_base/views/account_cutoff.xml#L322-L334
and this is in account_cutoff_prepaid, v13.0
https://github.com/OCA/account-closing/blob/f6f0cac1d34c52f3fbb6373420e3cbe2671110d4/account_cutoff_prepaid/views/account_cutoff.xml#L185-L205
This repeats for expenses as well

**Comment by iwkse** [comment]
@alexis-via what do you think?

**Comment by alexis-via** [comment]
@iwkse Please read https://github.com/OCA/account-closing/issues/133 
You have ported a feature that is already present this project v14 branch for a long time!!!

**Pull request closed without merging**
