### PR TITLE
[ADD] Add account_move_check_period module

### PR DESCRIPTION
**Pull request by ehdem**
This module adds contraint when creating an entry
with a closed period

### CODE REVIEW

**Comment by sbidoul** [comment]
Hello @ehdem 

Can you elaborate a bit the purpose of the module? I would say that if Odoo lets the user enter an entry in a closed period it is a bug that should be resolved with an Odoo and/or OCB PR.

Also note that this repository is dedicated to end-of-period cutoff so it is probably not the right place for such a module.

As a side note, you may be interested in this module: https://github.com/OCA/account-financial-tools/tree/8.0/account_journal_period_close (also available in 7.0).

**Comment by ehdem** [comment]
@sbidoul : For example, you can create manually a journal item with a closed period.
Go to Accounting/Journal entries/Journal items; in the form you can list of closed and opened period.

**Comment by sbidoul** [comment]
@ehdem at least on 8.0 you can't create entries in closed period from the journal items view.
Closed periods are in the list because this view is also used for searching so that makes sense.

So if 7.0 allows it, it is clearly a bug and I think it should be treated with an upstream PR instead of a module (I see no reason why Odoo would not accept a PR fixing that on 7.0).

**Comment by sbidoul** [comment]
At this stage, I'm :-1: for this one as I believe this should be fixed upstream and/or in OCB.

**Comment by sbidoul** [comment]
No feedback for a long period. Closing.

**Pull request closed without merging**
