### PR TITLE
[WIP] Migrate cutoff accrual picking from launchpad

### PR DESCRIPTION
**Pull request by jcoux**

### CODE REVIEW

**Comment by gurneyalex** [comment]
@alexis-via @fclementic2c your feedback on this is very welcome. I'm not sure about the translations.

**Comment by gurneyalex** [comment]
@alexis-via when I test on my customer's production data, I get a number of pickings selected which are _not_ in state 2B invoiced, which strikes me as very odd. Did I misunderstand the whole process?!

**Comment by alexis-via** [comment]
@gurneyalex it takes the picking before the cutoff date that are:
- to be invoiced
- invoice, with an invoice AFTER cutoff date

**Comment by gurneyalex** [comment]
@alexis-via I think the issue comes from the lack of data from stock_picking_invoice_link when initializing the database. I'm trying to populate the link table for purchase orders to see if things are improved.

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
