### PR TITLE
[16.0][FIX] account_cutoff_picking: is not an app

### PR DESCRIPTION
**Pull request by andreampiovesana**
"application": False

### CODE REVIEW

**Comment by andreampiovesana** [comment]
change please

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by andreampiovesana — COMMENTED** [review]
PLEASE MERGE

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Sorry, I can't merge this commit message. I will merge a separate PR with the corrected commit message.

**Comment by AaronHForgeFlow** [comment]
This is being merged in here: https://github.com/OCA/account-closing/pull/295 with a proper commit message

**Pull request closed without merging**
