### PR TITLE
[16.0][MIG] account_multicurrency_revaluation (good branch)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Supersedes https://github.com/OCA/account-closing/pull/250, in order to include last commits from https://github.com/OCA/account-closing/pull/259.

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — COMMENTED** [review]
Why changing the tests?

**Comment by MiquelRForgeFlow** [comment]
> Why changing the tests?

It's a partial revert of https://github.com/OCA/account-closing/pull/263/commits/084fd02b415e14d60a3efc0152f75991f6f0883e. It has to do with Odoo and how it handles things and reconciliation, I won't try to fully analyze why.

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by lk-eska** [comment]
is it only me who is getting this error:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/data/odoo-addons-dir/account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py", line 330, in revaluate_currency
    revaluations = account_ids.compute_revaluations(
  File "/mnt/data/odoo-addons-dir/account_multicurrency_revaluation/model/account.py", line 251, in compute_revaluations
    self.env.cr.execute(query, params)
  File "/opt/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: invalid reference to FROM-clause entry for table "account_account"
LINE 43:             AND ("account_account"."company_id" IS NULL  OR ...
                          ^
HINT:  Perhaps you meant to reference the table alias "acc".

**Comment by MiquelRForgeFlow** [comment]
@lk-eska it should be fixed in https://github.com/OCA/account-closing/pull/282.

**Pull request merged**
