### PR TITLE
14.0 mig account fiscal year closing

### PR DESCRIPTION
**Pull request by matteoopenf**
fix create and write  https://github.com/OCA/account-closing/pull/169

### CODE REVIEW

**Comment by matteoopenf** [comment]
@elvise  any idea how I can fix travis?
2022-07-13 09:27:25,213 6570 ERROR openerp_test odoo.modules.loading: At least one test failed when loading the modules.
2022-07-13 09:27:25,220 6570 INFO openerp_test odoo.service.server: Starting post tests
2022-07-13 09:27:25,227 6570 INFO openerp_test odoo.addons.account_invoice_start_end_dates.tests.test_invoice_start_end_dates: Starting TestInvoiceStartEndDates.test_invoice ...
2022-07-13 09:27:25,987 6570 INFO openerp_test odoo.service.server: 1 post-tests in 0.77s, 266 queries
2022-07-13 09:27:25,987 6570 ERROR openerp_test odoo.tests.runner: 0 failed, 1 error(s) of 13 tests when loading database 'openerp_test'
2022-07-13 09:27:25,987 6570 INFO openerp_test odoo.service.server: Initiating shutdown
2022-07-13 09:27:25,987 6570 INFO openerp_test odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2022-07-13 09:27:26,173 6570 INFO openerp_test odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections
----------
ERROR: setUpClass (odoo.addons.account_fiscal_year_closing.tests.test_account_fiscal_year_closing.TestAccountFiscalYearClosing)
Traceback (most recent call last):
  File "/home/travis/odoo-14.0/odoo/tests/common.py", line 173, in _handleClassSetUp
    setUpClass()
  File "/home/travis/build/OCA/account-closing/setup/account_fiscal_year_closing/odoo/addons/account_fiscal_year_closing/tests/test_account_fiscal_year_closing.py", line 15, in setUpClass
    super().setUpClass()
  File "/home/travis/odoo-14.0/addons/account/tests/common.py", line 27, in setUpClass
    assert 'post_install' in cls.test_tags, 'This test requires a CoA to be installed, it should be tagged "post_install"'
AssertionError: This test requires a CoA to be installed, it should be tagged "post_install"
 
Module account_fiscal_year_closing: 0 failures, 1 errors of 0 tests
At least one test failed when loading the modules.
0 failed, 1 error(s) of 13 tests when loading database 'openerp_test'
Message not found: 'Modules loaded.'

**Comment by matteoopenf** [comment]
@elvise I fix the problem and all is green and I think now all it is ok

**Review by patrickt-oforce — APPROVED** [review]

**Review by amosdisabatino — APPROVED** [review]

**Comment by matteoopenf** [comment]
@sergiocorato @SimoRubi  is it possibile have a review and after merge?

**Comment by matteoopenf** [comment]
@elvise  for you is it ok the pr?
thannk you

**Comment by elvise** [comment]
> @elvise for you is it ok the pr? thannk you

for me yes

**Comment by matteoopenf** [comment]
> > @elvise for you is it ok the pr? thannk you
> 
> for me yes

can you approve?
Thank you

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/accounting-maintainers could this be reviewed?

**Comment by matteoopenf** [comment]
@OCA/accounting-maintainers is possibile merge?

**Comment by matteoopenf** [comment]
@SimoRubi @SirTakobi  is ok for you?

**Comment by matteoopenf** [comment]
@sergiocorato  is ok now for you?

**Comment by matteoopenf** [comment]
@[petrus-v](https://github.com/petrus-v) review?

**Comment by matteoopenf** [comment]
[mde-spring](https://github.com/mde-spring) review?

**Comment by francesco-ooops** [comment]
@OCA/accounting-maintainers any chance to review?

**Comment by rafaelbn** [comment]
Helllo, I've never used this module. I could review it this weekend if you could record a little video explaining details. I'll try it!

**Comment by matteoopenf** [comment]
> Helllo, I've never used this module. I could review it this weekend if you could record a little video explaining details. I'll try it!

Hi, we write a little Manual I attach the manual, said me if all is ok for you
[Odoo_-_Manuale_-_Chiusura_Anno_fiscale.pdf](https://github.com/OCA/account-closing/files/9279739/Odoo_-_Manuale_-_Chiusura_Anno_fiscale.pdf)
 
Thank you

**Comment by elvise** [comment]
@pedrobaeza as this is a good for to merge, what do you think about this one?

**Comment by pedrobaeza** [comment]
Merging based on existing reviews:

/ocabot merge nobump

**Pull request merged**
