### PR TITLE
[11.0] account multicurrency revaluation improvements

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Comment by grindtildeath** [comment]
@oleksandrpaziuk @mpanarin @simahawk @yvaucher @fclementic2c 
As you guys worked on or reviewed #64, please have a look at this.

**Review by simahawk — CHANGES_REQUESTED** [review]
LGTM. Missing: module name in commits, module version upgrade.

**Review by mpanarin — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]
LGTM! :+1:

**Comment by grindtildeath** [comment]
@simahawk Version bumped, commits squashed

**Review by simahawk — APPROVED** [review]

**Comment by grindtildeath** [comment]
@yvaucher @fclementic2c Let's merge this ? There are no breaking changes and it's fixing an unfinished migration which shouldn't have been merged in the first time.

**Review by feketemihai — APPROVED** [review]

**Pull request merged**
