### PR TITLE
Forward port 7.0 until 856f3881aba

### PR DESCRIPTION
**Pull request by sbidoul**
The actual conflict resultion commit is cf4c5bf0a0932700b92ee13ad159cfc94cfcf811, best viewed in gitk

Preparing 8.0 migration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Seems good, although I think Travis it's going to fail due to an error on upstream.

**Comment by bwrsandman** [comment]
@pedrobaeza seems like a MQT bug

**Comment by pedrobaeza** [comment]
Yeah, you're right. Rebuild and now green.

:+1:

**Comment by guewen** [comment]
:+1:

**Comment by sbidoul** [comment]
Is this one good for merging? Then I'll submit the 8.0 port of account_cutoff_prepaid.

**Comment by pedrobaeza** [comment]
5 days and 2 reviews... so I merge!

**Pull request merged**
