### PR TITLE
[15.0][MIG] account_cutoff_base

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
@alexis-via can you pls take a look?

**Comment by yankinmax** [comment]
@sbidoul can you pls approve the workflow?

**Comment by yankinmax** [comment]
@simahawk can you pls approve the workflow?

**Review by alexis-via — APPROVED** [review]
Tested, works fine.

**Comment by alexis-via** [comment]
I propose a small improvement here: https://github.com/yankinmax/account-closing/pull/1

**Pull request merged**
