### PR TITLE
[FIX][account_fiscal_year_closing] fix check move_ids is valorize

### PR DESCRIPTION
**Pull request by matteoopenf**

### CODE REVIEW

**Comment by matteoopenf** [comment]
@OCA/community-maintainers  is it possibile to merge or not?

**Comment by dreispt** [comment]
Hello @matteoopenf , reviews are needed to be able to merge

**Review by sergiocorato — APPROVED** [review]
LGTM

**Comment by matteoopenf** [comment]
> /ocabot merge patch

Thanks

**Pull request merged**
