### PR TITLE
Migrate account multicurrency revaluation to 8.0

### PR DESCRIPTION
**Pull request by matthieuchoplin**
This is a minimal migration where:
- I have made the module installable
- The yml tests are passing

I think that in a next PR, we could port the code to the new API.

What do you think? Should I migrate to the new API in this PR or an other one?

Thanks

### CODE REVIEW

**Comment by matthieuchoplin** [comment]
I can see that the dependency missing (base_headers_webkit) is in an other repository: https://github.com/OCA/webkit-tools/tree/8.0/__unported__
Should I move it in this repository?
What is the logic here?

**Comment by pedrobaeza** [comment]
No, you just need to move out of unported in its repo, and add to oca_dependencies.txt or Travis the reference to that repository.

**Comment by matthieuchoplin** [comment]
Thank you for your answer @pedrobaeza . I noticed that the repo is already referenced in .travis.yml with 

```
- git clone https://github.com/OCA/webkit-tools ${HOME}/webkit-tools -b ${VERSION}
```

I also noticed that there is a PR (https://github.com/OCA/webkit-tools/pull/10) for porting the module base_headers_webkit that is blocked by a bug in Odoo: https://github.com/odoo/odoo/issues/2334

However, this bug in Odoo has been closed. Some workaround have been proposed...

**Comment by matthieuchoplin** [comment]
Aaaaaah! I just realised that the module account_multicurrency_revaluation that was in **unported** was not up to date! I need to start again from the branch https://github.com/OCA/account-closing/tree/7.0 this time...

**Pull request closed without merging**
