### PR TITLE
[15.0][FWP] account_multicurrency_revaluation

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/account-closing/pull/242.

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
Code review LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LG!

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Pull request merged**
