### PR TITLE
[10.0][FIX] Currency revaluation report wont print

### PR DESCRIPTION
**Pull request by pepetreshere**

### CODE REVIEW

**Comment by fclementic2c** [comment]
strange, I because I can print it on my test local instance

**Review by grindtildeath — CHANGES_REQUESTED** [review]
Good catch ! Please increase module version number.

@fclementic2c Following error appears with 10.0 branch when printing the report 
```
2018-01-29 11:18:15,160 1 ERROR test_revaluation odoo.service.report: Exception: External ID not found in the system: account_multicurrency_revaluation_report.curr_unrealized
Traceback (most recent call last):
  File "/opt/odoo/src/odoo/service/report.py", line 94, in go
    result, format = odoo.report.render_report(cr, uid, ids, object, datas, context)
  File "/opt/odoo/src/odoo/report/__init__.py", line 19, in render_report
    return env['ir.actions.report.xml'].render_report(ids, name, data)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_actions.py", line 232, in render_report
    return self.env['report'].get_pdf(res_ids, report, data=data), 'pdf'
  File "/opt/odoo/src/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/opt/odoo/src/addons/report/models/report.py", line 135, in get_html
    return report_model.render_html(docids, data=data)
  File "/opt/odoo/external-src/account-closing/account_multicurrency_revaluation/report/currency_unrealized_report.py", line 95, in render_html
    return self.env['report'].render(self._name[7:], docargs)
  File "/opt/odoo/src/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_ui_view.py", line 1043, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_ui_view.py", line 950, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_model.py", line 1085, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/opt/odoo/src/odoo/addons/base/ir/ir_model.py", line 1076, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<string>", line 2, in xmlid_lookup
  File "/opt/odoo/src/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_model.py", line 1065, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: account_multicurrency_revaluation_report.curr_unrealized
2018-01-29 11:18:15,385 1 ERROR test_revaluation odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/odoo/src/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/src/addons/web/controllers/main.py", line 1480, in index
    request.session.db, request.session.uid, request.session.password, report_id])
  File "/opt/odoo/src/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/src/odoo/service/report.py", line 35, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/src/odoo/service/report.py", line 142, in exp_report_get
    return _check_report(report_id)
  File "/opt/odoo/src/odoo/service/report.py", line 120, in _check_report
    raise UserError('%s: %s' % (exc.message, exc.traceback))
UserError: (u"External ID not found in the system: account_multicurrency_revaluation_report.curr_unrealized: (<type 'exceptions.ValueError'>, ValueError('External ID not found in the system: account_multicurrency_revaluation_report.curr_unrealized',), <traceback object at 0x7f0a3023d3f8>)", '')
```

**Comment by grindtildeath** [comment]
@pepetreshere Could you also fix the unittest ? Cf travis red.

**Comment by pepetreshere** [comment]
HI @grindtildeath, I will give it a try

**Comment by grindtildeath** [comment]
@pepetreshere The issue in test is here as we need the same report name : https://github.com/OCA/account-closing/blob/10.0/account_multicurrency_revaluation/tests/test_currency_revaluation_report.py#L21
When it's fixed and version is increased, we can merge your PR.

**Comment by grindtildeath** [comment]
Fixed in #77 because no answer for past 5 months.
@fclementic2c Can you please close this ?

**Pull request closed without merging**
