### PR TITLE
[Fix] use company from journal instead of logged in user

### PR DESCRIPTION
**Pull request by kenvac**
Fix for issue #1

### CODE REVIEW

**Comment by kenvac** [comment]
As requested, new pull request created for branch 7.0

**Comment by pedrobaeza** [comment]
Same as master branch :+1:

**Comment by kenvac** [comment]
Can we please merge this into 7.0 branch please?

**Comment by pedrobaeza** [comment]
We need at least two approvals for merging. Let's wait for a second one a while, and if it won't come, we decide.

Regards.

**Comment by rvalyi** [comment]
:+1: nice fix, thanks

**Comment by pedrobaeza** [comment]
I proceed with the merge.

Regards.

**Pull request merged**
