### PR TITLE
[16.0] account_cutoff_base: update README

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by yankinmax — APPROVED** [review]
Little nitpickings:
also we need to change here https://github.com/OCA/account-closing/blob/16.0/account_cutoff_base/README.rst#account-cut-off-base
and here https://github.com/OCA/account-closing/blob/1315dd8e3e3a170cc0542444f21e99579d560419/account_cutoff_base/static/description/index.html#L377
Thanks

**Comment by alexis-via** [comment]
@yankinmax these 2 other files are auto-generated from the readme subdir

**Comment by yankinmax** [comment]
@alexis-via thanks for explanation

**Pull request merged**
