### PR TITLE
[10.0][FIX] fix account_multicurrency_revaluation test

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by guewen** [comment]
@oleksandrpaziuk can you base your work on #77 using a revaluation company? It seems the test pass only because of the change of the rate to 1.0, which is probably only hiding the issue.

**Comment by fclementic2c** [comment]
@sbidoul better ?

**Comment by ghost** [comment]
As I understand correctly test was made to test currency difference. And in the original test, we has EUR to USD comparison. After new changes in odoo, we can't change currency in the company so I swap currency and now we test USD to EUR with same rates. That's why test pass. If it is the wrong idea than I can use a new company with EUR to USD comparison like in #77

**Comment by grindtildeath** [comment]
Please close in favour of #77

**Pull request closed without merging**
