### PR TITLE
[13.0][IMP]account_multicurrency_revaluation: Auto-Post Entries Setting

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
Adds the possibility of not posting the Entries automatically.
cc @ForgeFlow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍🏼

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM!

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Please check if forward port is needed.

**Pull request merged**
